### PR TITLE
Update tar

### PR DESCRIPTION
**Pull request by MGVining**
PT: https://www.pivotaltracker.com/story/show/179941950

This repo is pulled into IA-Desktop.
It had two instances of tar at 4.4.1 and 4.4.8, both have been deduped to an explicit 4.4.19.
It also had sass-loader 7.1.0, which was preventing IA-Desktop from using dart-sass, locking it on a version 2.2.2 tar.

---------------

Changes are small, but not sure how to test without pushing here and checking IA-Desktop functionality.

### CODE REVIEW

**Review by sdkester — COMMENTED** [review]
@MGVining If you want to make changes here, and possibly iterate on them, then you need to update the "version" semver in package.json. 

In this branch, run `npm version 2.1.6-rc.1` and push the changes to github. Then in your IAD working branch, change the git url to match: `"@csnw/react-scripts": "git+https://github.com/CSNW/react-scripts.git#2.1.6-rc.1",`. 

When you're all done, run `npm version 2.1.6` and update IAD accordingly

**Comment by MGVining** [comment]
@sdkester done fiddling versions here.

**Review by sdkester — APPROVED** [review]

**Comment by sdkester** [comment]
@MGVining Please put a link to the IAD pull request here when you're ready, or mention this pull request in the IAD pull request to cross link them.

**Comment by MGVining** [comment]
Updated to accommodate desktop changes here:
https://github.com/CSNW/ia-desktop/pull/3984

**Pull request merged**
